import type { Producto, Sede } from './types'

export const productosMock: Producto[] = [
  {
    id: 'p1',
    nombre: 'Cemento Gris Estructural',
    marca: 'Argos',
    tipo: 'saco',
    presentacion: 'Saco 50 kg',
    precio: 32500,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p2',
    nombre: 'Cemento Uso General',
    marca: 'Holcim',
    tipo: 'saco',
    presentacion: 'Saco 42.5 kg',
    precio: 28900,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p3',
    nombre: 'Cemento Blanco Premium',
    marca: 'Cemex',
    tipo: 'saco',
    presentacion: 'Saco 50 kg',
    precio: 45200,
    imagen: '/images/saco-blanco.png',
  },
  {
    id: 'p4',
    nombre: 'Mortero Seco Premezclado',
    marca: 'Argos',
    tipo: 'saco',
    presentacion: 'Saco 40 kg',
    precio: 21500,
    imagen: '/images/saco-mortero.png',
  },
  {
    id: 'p5',
    nombre: 'Cemento a Granel Tipo I',
    marca: 'Argos',
    tipo: 'granel',
    presentacion: 'Tonelada (granel)',
    precio: 580000,
    imagen: '/images/granel.png',
  },
  {
    id: 'p6',
    nombre: 'Cemento a Granel Petrolero',
    marca: 'Cemex',
    tipo: 'granel',
    presentacion: 'Tonelada (granel)',
    precio: 642000,
    imagen: '/images/granel.png',
  },
]

export const sedesMock: Sede[] = [
  {
    id: 's1',
    nombre: 'Obra Torre Central',
    tipo: 'obra',
    direccion: 'Cra 45 # 26-85',
    ciudad: 'Bogotá',
    contactoNombre: 'Ing. Marcela Ríos',
    contactoTelefono: '3104567890',
  },
  {
    id: 's2',
    nombre: 'Punto de Venta Norte',
    tipo: 'punto_venta',
    direccion: 'Calle 170 # 8-32',
    ciudad: 'Bogotá',
    contactoNombre: 'Carlos Méndez',
    contactoTelefono: '3201234567',
  },
  {
    id: 's3',
    nombre: 'Obra Conjunto Las Palmas',
    tipo: 'obra',
    direccion: 'Av. Las Palmas km 12',
    ciudad: 'Medellín',
    contactoNombre: 'Ing. Julián Vélez',
    contactoTelefono: '3009876543',
  },
  {
    id: 's4',
    nombre: 'Punto de Venta Sur',
    tipo: 'punto_venta',
    direccion: 'Cra 50 # 8 Sur-12',
    ciudad: 'Cali',
    contactoNombre: 'Andrea Lozano',
    contactoTelefono: '3157654321',
  },
]
