import type { Producto, Sede } from './types'

export const productosMock: Producto[] = [
  {
    id: 'p1',
    codigo: 'COD-0042',
    nombre: 'Cemento Gris Estructural',
    marca: 'San Marcos',
    tipo: 'saco',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 32500,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p2',
    codigo: 'COD-0043',
    nombre: 'Cemento Uso General',
    marca: 'San Marcos',
    tipo: 'saco',
    presentacion: 'Saco 25 kg',
    unidad: 'Bulto 25kg',
    precio: 28900,
    iva: 0.19,
    imagen: '/images/saco-gris.png',
  },
  {
    id: 'p3',
    codigo: 'COD-0051',
    nombre: 'Cemento Blanco Premium',
    marca: 'San Marcos',
    tipo: 'saco',
    presentacion: 'Saco 50 kg',
    unidad: 'Bulto 50kg',
    precio: 45200,
    iva: 0.19,
    imagen: '/images/saco-blanco.png',
  },
  {
    id: 'p4',
    codigo: 'COD-0067',
    nombre: 'Mortero Seco Premezclado',
    marca: 'San Marcos',
    tipo: 'saco',
    presentacion: 'Saco 40 kg',
    unidad: 'Bulto 40kg',
    precio: 21500,
    iva: 0.19,
    imagen: '/images/saco-mortero.png',
  },
  {
    id: 'p5',
    codigo: 'COD-0108',
    nombre: 'Cemento a Granel Tipo I',
    marca: 'San Marcos',
    tipo: 'granel',
    presentacion: 'Tonelada (granel)',
    unidad: 'Ton',
    precio: 580000,
    iva: 0.19,
    imagen: '/images/granel.png',
  },
  {
    id: 'p6',
    codigo: 'COD-0109',
    nombre: 'Cemento a Granel Petrolero',
    marca: 'San Marcos',
    tipo: 'granel',
    presentacion: 'Tonelada (granel)',
    unidad: 'Ton',
    precio: 642000,
    iva: 0.19,
    imagen: '/images/granel.png',
  },
]

export const sedesMock: Sede[] = [
  {
    id: 's1',
    nombre: 'Obra Torre Central',
    tipo: 'obra',
    direccion: 'Cra 45 # 26-85',
    ciudad: 'Bogotá',
    contactoNombre: 'Ing. Marcela Ríos',
    contactoTelefono: '3104567890',
  },
  {
    id: 's2',
    nombre: 'Punto de Venta Norte',
    tipo: 'punto_venta',
    direccion: 'Calle 170 # 8-32',
    ciudad: 'Bogotá',
    contactoNombre: 'Carlos Méndez',
    contactoTelefono: '3201234567',
  },
  {
    id: 's3',
    nombre: 'Obra Conjunto Las Palmas',
    tipo: 'obra',
    direccion: 'Av. Las Palmas km 12',
    ciudad: 'Medellín',
    contactoNombre: 'Ing. Julián Vélez',
    contactoTelefono: '3009876543',
  },
  {
    id: 's4',
    nombre: 'Punto de Venta Sur',
    tipo: 'punto_venta',
    direccion: 'Cra 50 # 8 Sur-12',
    ciudad: 'Cali',
    contactoNombre: 'Andrea Lozano',
    contactoTelefono: '3157654321',
  },
]
